name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        # setup-node has built-in npm caching support!
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Install dependencies
      # 'npm ci' is the best practice for CI/CD. 
      # It strictly follows your package-lock.json and is faster than 'npm install'.
      run: npm ci
      shell: bash